os:
  - linux

services:
  - docker

language: generic

before_install:
  - packages/travis/travis.sh before_install

script:
  - packages/travis/travis.sh script

notifications:
  irc: "irc.rusnet.org.ru#ada-commits"

deploy:
  skip_cleanup: true
  on:
    condition: "$TRAVIS_OS_NAME = linux"
  provider: bintray
  file: packages/travis/bintray.json
  user: reznikmm
  key:
    secure: "eEH0e2VwxEYnG5ufniSUHbZBrnKwXSXTZ5qUctwGAoptCfWKKeLMhDj33aL5rpayLZXSyKHnVfMO3YhG5i8CK4nn2JRZ8L01oPWWWOrJYH1uUzrRSPsLYhvgxiYeYXfOiypr24Qwi/N+7x9RnwbIA73IaMhDej3a6XneRg9GTr+Rsv0CVfD9cdh8XGRKz9N6OIcHGbqj9dEgtqwSv1IUrTabM4/cyvht9MBO3YnwCZxpmeLPWWa5DldOcZCbYxSjRvkWFg8bmqVOcKSJRsb7ZI3l8N/F+bGJhlyp/2/B82uD2OrbqxXUw8Q2OAdj5eNnTYPqYGs1G6OaOg1qt1P34SumkcBxVaxnlM6PHTAKqk0w2yHpJJX2vgL9MVP4ISvCAzV4E9+A/KmCxLhllNuFL5H4+4qAMN3DbFwr6l0Xy+dWrpLyvRRBRR0P8ErZYTqW1UHOA8w1J4bC+HkGniXjZqzcla4rdpPxr/LbYeO1Whu8s5tYVzzGW9N2Qg/L/1S8Y7JsOWdj66w086sxDr/tiwtqRfe9zwtq7H56K7Hl1o56JdlB+F587e5Eq03jFKw8M9YjdBRrVyQKJK4aayFBa63/CXuC5o/teX9TUqeHVDZySSryHF+aLxRSqm6tGoDKRHUZjexuNAzgR8RQAOvr5CGf7R1A0DI5q7Vfbmw74O8="
