os:
  - linux

services:
  - docker

language: generic

before_install:
  - packages/travis/travis.sh before_install

script:
  - packages/travis/travis.sh script

notifications:
  irc: "irc.rusnet.org.ru#ada-commits"

deploy:
  skip_cleanup: true
  on:
    condition: "$TRAVIS_OS_NAME = linux"
  provider: bintray
  file: packages/travis/bintray.json
  user: reznikmm
  key:
    secure: aiG1vPXgd8Bnezs/T4CfCB40Mmf6PdXARv7aboqC5/iPFuk9cz6C27lEGHfwYKML7W7Cbh2VkwUw4jmKV22oJeYcJtOFFM8KKftCFGSZHQpBK0frBJfKe+A7WK0KxMnB9BhkK+CPlpFCCc3KOFrH5slEIV9OOorlXwQMKuK7YtvGVZRvUj9yFTDUshEhaJnl8pBTHiFGm2yS18oFpFjL43N+YBACgHetPPFStEw3SfXxfcs8IGtHP3tUF3w42L2CSwRYB/gnmlE1D8WI37dNBWEE0h6TUAHn3GztjRUoTPlsjX/xlh0+LSCFrE0k76N9JJTTSwMDWKKTBYWKtyf1VWwtyxICuGrZy36f4VWa0WcQvbQcfKKvww2Ry7Lje21/l2UlSFE/d4sKJsUdSpXEafyEW3cn6yGRocy+9mpGtG5a7Pj4JgURkXNB+YiRrTMFNvpL8ujxRTbppq66/F99KPJHpFYYmIHjWrnz23SlPd8tVK+GTjx35F1Hua9PD6zMOpRbBVm7XpuQIZJ8EgaGcWXlTo2g/Iq06UE2Fj2R40B+x1cUlmGICmfJKhvnMspvanA2/on8BFRDGiyNbBySEaCVcF9w2mA3l5IdCgvfzLhJJWAsNOZ11G82livTD3Ek1JsYzr/S9bkgIIyxxs4KA5Mh4EMWMMroQGO/E/0He3c=
