--  Copyright (c) 2015-2017 Maxim Reznik <reznikmm@gmail.com>
--
--  SPDX-License-Identifier: MIT
--  License-Filename: LICENSE
-------------------------------------------------------------

with Matreshka.Internals.Unicode;

generic
   with function To_Class (Value : Matreshka.Internals.Unicode.Code_Point)
                              return Character_Class;

   with function Switch (S : State; Class : Character_Class) return State;

   with function Rule (S : State) return Rule_Index;

   Error_State : State;

package Incr.Lexers.Batch_Lexers.Generic_Lexers is
   --  @summary
   --  Generic Batch Lexer
   --
   --  @description
   --  This is an implementation of batch lexical analyser. It gets functions
   --  generated by uaflex as tables subunut.

   type Batch_Lexer is new Batch_Lexers.Batch_Lexer with null record;

   overriding procedure Get_Token
     (Self   : access Batch_Lexer;
      Result : out Rule_Index);

end Incr.Lexers.Batch_Lexers.Generic_Lexers;
